#!/usr/bin/env bash
# =============================================================================
# terminal-kniferoll | macOS Installer (Shell + Projector)
# =============================================================================
#
# Supply chain controls: lib/supply_chain_guard.sh is sourced below.
# Always runs in strict mode (TLS enforced, hashes verified where available).
# =============================================================================

set -Eeuo pipefail
export HOMEBREW_NO_AUTO_UPDATE=1

# ── Ensure brew is findable regardless of invoking shell's PATH ───────────────
# is_installed("brew") uses command -v, which is PATH-dependent. When the script
# is invoked from a non-login shell, via sudo (which resets PATH to a secure
# default), from a GUI, or from a CI context, /opt/homebrew/bin may be absent.
# Prepend canonical prefixes NOW — before any detection logic — so the check at
# the Homebrew bootstrap section never false-negatives on an installed brew.
#   Apple Silicon: /opt/homebrew/bin   Intel/universal: /usr/local/bin
for _brew_prefix in /opt/homebrew /usr/local; do
    if [[ -x "${_brew_prefix}/bin/brew" && ":$PATH:" != *":${_brew_prefix}/bin:"* ]]; then
        export PATH="${_brew_prefix}/bin:${_brew_prefix}/sbin:$PATH"
    fi
done
unset _brew_prefix

# ── TTY-guarded color palette ─────────────────────────────────────────────────
if [ -t 1 ]; then
  RED='\033[0;31m';   GREEN='\033[0;32m';  YELLOW='\033[1;33m'
  CYAN='\033[0;36m';  BOLD='\033[1m';      DIM='\033[2m';       RESET='\033[0m'
  ORANGE='\033[38;5;208m'; STEEL='\033[38;5;249m'
  HERB='\033[38;5;106m';   BLADE='\033[38;5;255m'
else
  RED=''; GREEN=''; YELLOW=''; CYAN=''; BOLD=''; DIM=''; RESET=''
  ORANGE=''; STEEL=''; HERB=''; BLADE=''
fi

# ── Log file ──────────────────────────────────────────────────────────────────
LOG_FILE="$HOME/.terminal-kniferoll/logs/install_$(date +%Y%m%d_%H%M%S).log"
mkdir -p "$(dirname "$LOG_FILE")"

_log() {
  local level="$1" msg="$2"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$level] $msg" >> "$LOG_FILE"
}

# ── Logging helpers ───────────────────────────────────────────────────────────
ok()     { echo -e "${GREEN}[✓]${RESET} ${HERB}$*${RESET}";   _log "OK"    "$*"; }
info()   { echo -e "${CYAN}[→]${RESET} $*";                   _log "INFO"  "$*"; }
warn()   { echo -e "${ORANGE}[~]${RESET} $*";                 _log "WARN"  "$*"; }
skip()   { echo -e "${DIM}[~] skip: $*${RESET}";              _log "SKIP"  "$*"; }
err()    { echo -e "${RED}[✗]${RESET} $*";                    _log "ERROR" "$*"; }
die()    { echo -e "${RED}[✗] FATAL: $*${RESET}" >&2;         _log "ERROR" "FATAL: $*"; exit 1; }
banner() { echo -e "\n${BOLD}${CYAN}[ $* ]${RESET}";          _log "INFO"  "=== $* ==="; }
quip()   { echo -e "${DIM}  ⋮ $*${RESET}"; }

# ── Failed tools tracker ──────────────────────────────────────────────────────
FAILED_TOOLS=()

# shellcheck disable=SC2329  # invoked indirectly via ERR trap below
on_error() { warn "Unexpected failure at line $1: $2"; }
trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

# ── Helper: run with soft failure ────────────────────────────────────────────
run_optional() {
    local desc="$1"; shift
    info "$desc"
    if (set +Ee; "$@"); then ok "$desc"; return 0; fi
    warn "$desc — failed, continuing"
    return 0
}

# ── Helper: download URL to a secure temp file ───────────────────────────────
# Respects CURL_CA_BUNDLE if set (Zscaler managed-device mode).
download_to_tmp() {
    local url="$1" pattern="$2" tmp_file old_umask
    old_umask="$(umask)"
    umask 077
    tmp_file="$(mktemp "/tmp/${pattern}")"
    umask "$old_umask"
    chmod 600 "$tmp_file"
    local curl_opts=(--proto '=https' --tlsv1.2 -fsSL)
    [[ -n "${CURL_CA_BUNDLE:-}" && -f "${CURL_CA_BUNDLE}" ]] && \
        curl_opts+=(--cacert "$CURL_CA_BUNDLE")
    curl "${curl_opts[@]}" "$url" -o "$tmp_file"
    echo "$tmp_file"
}

# ── Helper: append line to file if absent ────────────────────────────────────
append_if_missing() {
    local file="$1" line="$2"
    touch "$file"
    grep -Fq "$line" "$file" || echo "$line" >> "$file"
}

# ── Write ~/.config/terminal-kniferoll/zscaler-env.sh (macOS) ────────────────
# Installer writes this file fresh on every run with absolute macOS detection
# paths. No $OSTYPE branching at runtime. All env vars derived from $ZSC_PEM.
write_zscaler_env_file() {
    local env_dir="$HOME/.config/terminal-kniferoll"
    local env_file="$env_dir/zscaler-env.sh"
    mkdir -p "$env_dir"
    local _tmp; _tmp="$(mktemp "$env_dir/zscaler-env-XXXXXX.sh")"
    chmod 644 "$_tmp"
    {
        printf '# Auto-generated by terminal-kniferoll installer. DO NOT EDIT.\n'
        printf '# OS: Darwin  Generated: %s\n\n' "$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        cat << 'ENVEOF'
ZSC_PEM=""
for _p in \
    "/Users/Shared/.certificates/zscaler.pem" \
    "$HOME/.config/terminal-kniferoll/ca-bundle.pem" \
    "/Library/Application Support/Zscaler/ZscalerRootCertificate-2048-SHA256.crt"
do
    if [ -s "$_p" ]; then ZSC_PEM="$_p"; break; fi
done
unset _p

if [ -n "$ZSC_PEM" ]; then
    export ZSC_PEM
    export CURL_CA_BUNDLE="$ZSC_PEM"
    export SSL_CERT_FILE="$ZSC_PEM"
    export REQUESTS_CA_BUNDLE="$ZSC_PEM"
    export NODE_EXTRA_CA_CERTS="$ZSC_PEM"
    export GIT_SSL_CAINFO="$ZSC_PEM"
    export AWS_CA_BUNDLE="$ZSC_PEM"
    export PIP_CERT="$ZSC_PEM"
    export HOMEBREW_CURLOPT_CACERT="$ZSC_PEM"
fi
ENVEOF
    } > "$_tmp"
    mv -f "$_tmp" "$env_file"
    ok "~/.config/terminal-kniferoll/zscaler-env.sh written (macOS)"
}

# ── Helper: yes/no prompt ────────────────────────────────────────────────────
ask_yes_no() {
    local prompt="$1"
    echo -en "${CYAN}[?] ${prompt} [Y/n] ${RESET}"
    read -r _reply
    [[ -z "$_reply" || "$_reply" =~ ^[Yy]$ ]]
}

# ── Helper: check if binary is on PATH ───────────────────────────────────────
is_installed() { command -v "$1" &>/dev/null; }

# ── Helper: check if macOS .app is installed ─────────────────────────────────
is_app_installed() {
    [[ -d "/Applications/$1.app" ]] || [[ -d "$HOME/Applications/$1.app" ]]
}

# ── Helper: detect MDM-managed / restricted device ───────────────────────────
is_restricted_device() {
    profiles status -type enrollment 2>/dev/null | grep -qi "yes"
}

# ── Zscaler splash-page helpers ───────────────────────────────────────────────
#
# Environment variables (all optional):
#   TERMINAL_KNIFEROLL_ZSCALER_AUTO_ACCEPT=1   (default) Try POST auto-accept.
#   TERMINAL_KNIFEROLL_ZSCALER_AUTO_ACCEPT=0   Skip auto-accept; go straight to manual.
#   TERMINAL_KNIFEROLL_ZSCALER_REASON="..."    Override form reason field value.

_splash_log_file="$HOME/.config/terminal-kniferoll/zscaler-splash.log"

_splash_log() {
    mkdir -p "$(dirname "$_splash_log_file")"
    printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$_splash_log_file"
}

# URL-encode a string using python3 (always available on macOS 12+).
_url_encode() { python3 -c "import sys,urllib.parse; print(urllib.parse.quote(sys.argv[1]))" "$1" 2>/dev/null || printf '%s' "$1"; }

# zscaler_attempt_auto_accept HTML SPLASH_URL COOKIE_JAR
# Parses a Zscaler acknowledgment HTML form, posts the acceptance, returns 0 on success.
zscaler_attempt_auto_accept() {
    local html="$1" splash_url="$2" cookie_jar="$3"

    _splash_log "--- auto-accept attempt: $splash_url"

    # Extract <form action="..."> (first form)
    local form_action
    form_action=$(printf '%s' "$html" | grep -oiE '<form[^>]+>' | head -1 | \
        grep -oiE 'action="[^"]+"' | sed 's/action="//;s/"//')
    if [[ -z "$form_action" ]]; then
        # single-quoted variant
        form_action=$(printf '%s' "$html" | grep -oiE "<form[^>]+>" | head -1 | \
            grep -oiE "action='[^']+'" | sed "s/action='//;s/'//")
    fi
    if [[ -z "$form_action" ]]; then
        _splash_log "no form action found — cannot auto-accept"
        return 1
    fi

    # Resolve relative action URL
    if [[ "$form_action" != http* ]]; then
        local _base; _base="$(printf '%s' "$splash_url" | grep -oE 'https?://[^/]+')"
        [[ "$form_action" == /* ]] && form_action="${_base}${form_action}" \
                                   || form_action="${_base}/${form_action}"
    fi

    # Collect hidden fields  →  name=value& pairs
    local post_data=""
    while IFS= read -r _field; do
        local _n _v
        _n=$(printf '%s' "$_field" | grep -oiE 'name="[^"]+"'  | head -1 | sed 's/name="//;s/"//')
        _v=$(printf '%s' "$_field" | grep -oiE 'value="[^"]*"' | head -1 | sed 's/value="//;s/"//')
        [[ -z "$_n" ]] && continue
        post_data+="$(_url_encode "$_n")=$(_url_encode "$_v")&"
    done < <(printf '%s' "$html" | grep -oiE '<input[^>]+type="hidden"[^>]*>' | head -30)

    # Explicit accept/acknowledge/continue button fields
    local _accept_name _accept_val
    _accept_name=$(printf '%s' "$html" | grep -oiE '<input[^>]+(name="(accept|acknowledge|agree|continue|proceed)")[^>]*>' | head -1 | \
        grep -oiE 'name="[^"]+"' | sed 's/name="//;s/"//')
    if [[ -n "$_accept_name" ]]; then
        _accept_val=$(printf '%s' "$html" | grep -oiE 'name="'"$_accept_name"'"[^>]*>' | head -1 | \
            grep -oiE 'value="[^"]*"' | sed 's/value="//;s/"//')
        post_data+="$(_url_encode "$_accept_name")=$(_url_encode "${_accept_val:-Agree}")&"
    else
        # Generic fallback fields that common Zscaler forms use
        post_data+="accept=Agree&agree=true&acknowledge=1&"
    fi

    # Reason/justification field
    local _reason="${TERMINAL_KNIFEROLL_ZSCALER_REASON:-Developer environment setup}"
    if printf '%s' "$html" | grep -qi 'name="reason"'; then
        post_data+="reason=$(_url_encode "$_reason")&"
    fi
    post_data="${post_data%&}"  # strip trailing &

    _splash_log "form_action: $form_action"
    _splash_log "post_fields: $post_data"

    # POST the form, replay cookies
    local curl_opts=(--proto '=https' --tlsv1.2 --max-time 20 -fsSL
                     -X POST --data "$post_data"
                     -H "Content-Type: application/x-www-form-urlencoded")
    [[ -n "${CURL_CA_BUNDLE:-}" && -f "${CURL_CA_BUNDLE}" ]] && curl_opts+=(--cacert "$CURL_CA_BUNDLE")
    [[ -f "$cookie_jar" ]] && curl_opts+=(-b "$cookie_jar" -c "$cookie_jar")

    local post_resp post_rc=0
    post_resp=$(curl "${curl_opts[@]}" "$form_action" 2>&1) || post_rc=$?

    if [[ "$post_rc" -ne 0 ]]; then
        _splash_log "POST failed (curl exit $post_rc)"
        return 1
    fi

    # Success: response is NOT an HTML splash page
    if ! printf '%s' "$post_resp" | grep -qi "<html\|<!DOCTYPE\|zscaler\|zpa_block\|access denied"; then
        _splash_log "auto-accept: SUCCESS"
        return 0
    fi

    _splash_log "auto-accept: POST returned another HTML page — failed"
    return 1
}

# zscaler_manual_prompt SPLASH_URL
# Shows a user-friendly box, opens the URL in the default browser, waits for Enter.
zscaler_manual_prompt() {
    local splash_url="$1"
    echo
    echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}${CYAN}║  Zscaler requires acknowledgment before this traffic is allowed  ║${RESET}"
    echo -e "${BOLD}${CYAN}╠══════════════════════════════════════════════════════════════════╣${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}                                                                  ${BOLD}${CYAN}║${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}  Open this URL in your browser and accept:                       ${BOLD}${CYAN}║${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}  ${YELLOW}${splash_url}${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}                                                                  ${BOLD}${CYAN}║${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}  Reason to give (if prompted): \"Developer environment setup\"    ${BOLD}${CYAN}║${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}                                                                  ${BOLD}${CYAN}║${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}  After accepting, return to this terminal and press ENTER        ${BOLD}${CYAN}║${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}  to continue.                                                    ${BOLD}${CYAN}║${RESET}"
    echo -e "${BOLD}${CYAN}║${RESET}                                                                  ${BOLD}${CYAN}║${RESET}"
    echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════════════════════════════╝${RESET}"
    echo
    # Auto-open in default browser on macOS (only in interactive TTY sessions)
    if [[ -t 1 ]]; then
        open "$splash_url" 2>/dev/null || true
        info "Opened $splash_url in your default browser"
    fi
    echo -en "${CYAN}[→] Press ENTER after accepting in your browser... ${RESET}"
    read -r _
}

# ── TLS preflight check ───────────────────────────────────────────────────────
# Curls the Homebrew install script endpoint and checks for:
#   - curl exit 60: SSL cert verification failure (Zscaler intercepting, untrusted)
#   - HTML response body: Zscaler/corporate acknowledgment splash page → try auto-accept
#   - Response contains "zscaler" body marker: explicit block marker
# Returns:
#   0  TLS clean — proceed
#   1  SSL cert error or unrecoverable block — caller should invoke setup_zscaler_trust
#   2  Splash page handled (auto-accepted or user manually accepted) — caller should re-run
# Caller must NOT proceed to brew/omz/git installs until this returns 0.
preflight_zscaler_check() {
    local test_url="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    local cookie_jar; cookie_jar="$(mktemp /tmp/zscaler-cookies-XXXXXX.txt)"
    local curl_opts=(--proto '=https' --tlsv1.2 --max-time 15 -fsSL
                     -c "$cookie_jar" -w '\n__EFFECTIVE_URL__%{url_effective}')
    [[ -n "${CURL_CA_BUNDLE:-}" && -f "${CURL_CA_BUNDLE}" ]] && \
        curl_opts+=(--cacert "$CURL_CA_BUNDLE")

    local raw exit_code=0
    raw=$(curl "${curl_opts[@]}" "$test_url" 2>&1) || exit_code=$?

    # Split write_out sentinel from body
    local effective_url response
    effective_url=$(printf '%s' "$raw" | grep '__EFFECTIVE_URL__' | sed 's/.*__EFFECTIVE_URL__//')
    response=$(printf '%s' "$raw" | grep -v '__EFFECTIVE_URL__')
    local splash_url="${effective_url:-$test_url}"

    # curl exit 60 = SSL certificate problem — Zscaler not yet trusted
    if [[ "$exit_code" -eq 60 ]]; then
        rm -f "$cookie_jar"
        warn "preflight: TLS certificate error (SSL verification failed)"
        warn "preflight: Zscaler is intercepting HTTPS and the cert is not trusted yet"
        return 1
    fi

    # Any other curl failure (network down, timeout, DNS)
    if [[ "$exit_code" -ne 0 ]]; then
        rm -f "$cookie_jar"
        warn "preflight: curl failed (exit $exit_code) — network may be unavailable"
        return 1
    fi

    # HTML response = Zscaler/corporate acknowledgment splash page
    if printf '%s' "$response" | grep -qi "<html\|<title\|<!DOCTYPE"; then
        warn "preflight: received HTML instead of a shell script"
        warn "preflight: possible Zscaler acknowledgment page at: $splash_url"

        if [[ "${TERMINAL_KNIFEROLL_ZSCALER_AUTO_ACCEPT:-1}" != "0" ]]; then
            info "preflight: attempting automatic Zscaler form acceptance..."
            if zscaler_attempt_auto_accept "$response" "$splash_url" "$cookie_jar"; then
                ok "preflight: auto-accept posted — re-validating TLS..."
                rm -f "$cookie_jar"
                return 2  # signal caller to re-run preflight
            fi
            warn "preflight: auto-accept failed — falling back to manual prompt"
        fi

        rm -f "$cookie_jar"
        zscaler_manual_prompt "$splash_url"
        return 2  # user accepted in browser, caller re-runs preflight
    fi

    rm -f "$cookie_jar"

    # Zscaler block-page body marker (no HTML wrapper)
    if printf '%s' "$response" | grep -qi "zscaler\|zpa_block\|access denied by zscaler"; then
        warn "preflight: Zscaler block-page marker in response body"
        return 1
    fi

    ok "preflight: TLS validated — raw.githubusercontent.com reachable, no interception detected"
    return 0
}

# ── Zscaler managed-device cert trust ────────────────────────────────────────
# Call AFTER preflight_zscaler_check returns non-zero.
# Builds a combined CA bundle (macOS system roots + Zscaler) and exports all
# cert env vars so every subsequent curl/brew/git/npm/pip/aws in this session
# inherits them — including oh-my-zsh's git clone.
#
# Detection order (macOS-only — no Linux paths in this script):
#   1. Previously built combined bundle  (fast path on re-run)
#   2. LM standard path: /Users/Shared/.certificates/zscaler.pem  (PDF-prescribed)
#   3. Zscaler app path  (ZIA/ZPA client default on macOS)
#   4. System Keychain export  (MDM-enrolled without Zscaler app)
#
# Flags:
#   --required   Die (exit non-zero) if no cert is found instead of returning 0.
#                Pass this when preflight already detected interception.
setup_zscaler_trust() {
    local required=false
    [[ "${1:-}" == "--required" ]] && required=true

    local zsc_pem=""
    local bundle_dir="$HOME/.config/terminal-kniferoll"
    local combined_bundle="$bundle_dir/ca-bundle.pem"
    mkdir -p "$bundle_dir"

    # 1. Fast path — prior installer run already built the bundle
    if [[ -s "$combined_bundle" ]]; then
        _zscaler_export_env "$combined_bundle"
        ok "Zscaler trust: using cached CA bundle"
        return 0
    fi

    # 2. LM standard path (Liberty Mutual Zscaler Developer Onboarding doc, Dec 2025)
    if [[ -s "/Users/Shared/.certificates/zscaler.pem" ]]; then
        zsc_pem="/Users/Shared/.certificates/zscaler.pem"
        info "Zscaler cert found at LM standard path (/Users/Shared/.certificates/)"
    fi

    # 3. Zscaler app path (ZIA/ZPA client default on macOS)
    if [[ -z "$zsc_pem" ]]; then
        local _zsc_app="/Library/Application Support/Zscaler/ZscalerRootCertificate-2048-SHA256.crt"
        if [[ -f "$_zsc_app" ]]; then
            zsc_pem="$_zsc_app"
            info "Zscaler cert found at Zscaler app path"
        fi
    fi

    # 4. System Keychain export (MDM-enrolled without Zscaler app or manual cert)
    if [[ -z "$zsc_pem" ]]; then
        local _tmp_ks; _tmp_ks="$(mktemp /tmp/zscaler-ks-XXXXXX.pem)"
        chmod 600 "$_tmp_ks"
        if security find-certificate -c "Zscaler" -a -p \
                /Library/Keychains/System.keychain > "$_tmp_ks" 2>/dev/null \
                && [[ -s "$_tmp_ks" ]]; then
            zsc_pem="$_tmp_ks"
            info "Zscaler cert exported from System Keychain"
        else
            rm -f "$_tmp_ks"
        fi
    fi

    if [[ -z "$zsc_pem" ]]; then
        if [[ "$required" == "true" ]]; then
            err "Zscaler TLS interception detected but no Zscaler root cert was found."
            err ""
            err "Remediation — run ONE of the following:"
            err "  1. Place the Zscaler cert at the LM standard path:"
            err "       /Users/Shared/.certificates/zscaler.pem"
            err "     (See: LM Zscaler Developer Onboarding doc, section 'Get the Required Certificate')"
            err "  2. Install the Zscaler client app (ZIA/ZPA) — it writes the cert automatically."
            err "  3. Import the cert into the System Keychain via IT/MDM."
            err ""
            err "After placing the cert, re-run: ./install_mac.sh"
            die "Cannot continue without Zscaler root cert on a managed device"
        fi
        skip "No Zscaler cert detected — assuming standard TLS (non-managed device)"
        return 0
    fi

    # Build combined bundle: macOS system roots + System keychain + Zscaler cert.
    # Write atomically (tmp + mv) so a crash mid-build doesn't leave a corrupt
    # file that the fast path would reuse on the next run.
    info "Building combined CA bundle for managed-device trust..."
    local _tmp_bundle; _tmp_bundle="$(mktemp "$bundle_dir/ca-bundle-XXXXXX.pem")"
    chmod 644 "$_tmp_bundle"
    {
        security find-certificate -a -p \
            /System/Library/Keychains/SystemRootCertificates.keychain 2>/dev/null || true
        security find-certificate -a -p \
            /Library/Keychains/System.keychain 2>/dev/null || true
        cat "$zsc_pem"
    } > "$_tmp_bundle"
    mv -f "$_tmp_bundle" "$combined_bundle"

    _zscaler_export_env "$combined_bundle"
    ok "Zscaler trust configured — $(wc -l < "$combined_bundle") cert lines in bundle"
    quip "curl, brew, git, npm, yarn, pip, aws cli will all trust this bundle in this session"
}

# ── Export all cert env vars for the current session ─────────────────────────
# Called by setup_zscaler_trust. Sets vars for every tool that does TLS in the
# install session — including git (for oh-my-zsh clone) and node/pip/aws.
_zscaler_export_env() {
    local bundle="$1"
    export CURL_CA_BUNDLE="$bundle"
    export HOMEBREW_CURLOPT_CACERT="$bundle"
    export SSL_CERT_FILE="$bundle"
    export GIT_SSL_CAINFO="$bundle"
    export NODE_EXTRA_CA_CERTS="$bundle"
    export REQUESTS_CA_BUNDLE="$bundle"
    export AWS_CA_BUNDLE="$bundle"
    export PIP_CERT="$bundle"
    export ZSC_PEM="$bundle"
}


# ── Cleanup: tools explicitly removed from this project ──────────────────────
cleanup_removed_tools() {
    local did_work=false

    # ── atuin — removed 2026-04-05: supply chain risk
    if is_installed "atuin" || brew list atuin &>/dev/null 2>&1; then
        did_work=true
        warn "atuin found — evicting (cut: supply chain risk)"
        brew list atuin &>/dev/null 2>&1 && \
            run_optional "Removing atuin (brew)" brew uninstall atuin || true
        [[ -d "$HOME/.atuin" ]] && \
            run_optional "Removing ~/.atuin data dir" rm -rf "$HOME/.atuin"
        [[ -f "$HOME/.zshrc" ]] && \
            sed -i '' '/command -v atuin.*atuin init zsh/d' "$HOME/.zshrc" 2>/dev/null || true
        ok "atuin — evicted"
    fi

    # ── mise — removed 2026-04-05: supply chain risk
    if is_installed "mise" || brew list mise &>/dev/null 2>&1; then
        did_work=true
        warn "mise found — evicting (cut: supply chain risk)"
        brew list mise &>/dev/null 2>&1 && \
            run_optional "Removing mise (brew)" brew uninstall mise || true
        [[ -d "$HOME/.local/share/mise" ]] && \
            run_optional "Removing ~/.local/share/mise data dir" \
                rm -rf "$HOME/.local/share/mise"
        ok "mise — evicted"
    fi

    "$did_work" || skip "No removed tools found — clean slate"
}

# ── Feature: ensure Rust toolchain ───────────────────────────────────────────
ensure_rust_toolchain() {
    if ! is_installed "cargo"; then
        # macOS: install rustup via Homebrew (supply-chain-safe; signed pkg).
        # Do NOT pipe sh.rustup.rs — violates docs/SUPPLY_CHAIN_RISK.md policy.
        run_optional "Installing rustup via Homebrew" brew install rustup
        [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env" || true
    fi
    if is_installed "rustup"; then
        rustup show active-toolchain &>/dev/null || \
            run_optional "Configuring rustup default stable" rustup default stable
        is_installed "cargo" || run_optional "Repairing Rust toolchain" rustup default stable
        [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env" || true
    fi
}

# ── Mission summary ───────────────────────────────────────────────────────────
print_summary() {
    banner "MISSION DEBRIEF"
    if [[ ${#FAILED_TOOLS[@]} -eq 0 ]]; then
        echo -e "${GREEN}${BOLD}  ALL SYSTEMS NOMINAL — zero casualties.${RESET}"
    else
        echo -e "${YELLOW}${BOLD}  MISSION COMPLETE WITH CASUALTIES:${RESET}"
        for t in "${FAILED_TOOLS[@]}"; do echo -e "  ${RED}[✗]${RESET}  $t"; done
        quip "Try: brew install <pkg> to retry failed items"
    fi
    echo
    echo -e "${DIM}  [→] Log saved to: ${LOG_FILE}${RESET}"
    _log "INFO" "Install complete. Failures: ${#FAILED_TOOLS[@]}"
}

# ── Help text ─────────────────────────────────────────────────────────────────
show_help() {
    echo "Usage: install_mac.sh [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --shell          Install shell environment only (skip projector)"
    echo "  --projector      Install projector tools only (skip shell)"
    echo "  --no-casks       Skip desktop application cask installs (iTerm2, Keka)"
    echo "  --interactive    Force interactive menu"
    echo "  --help           Show this help message and exit"
    echo ""
    echo "Default: shows grouped TUI (TTY) or full install (non-TTY)."
}

# ── TUI selector (bubbletea) ──────────────────────────────────────────────────
TUI_SELECTOR="$HOME/.terminal-kniferoll/bin/selector"

build_tui_selector() {
    local src="$SCRIPT_DIR/tui/selector"
    [[ -d "$src" ]] || return 1
    is_installed "go" || return 1
    mkdir -p "$(dirname "$TUI_SELECTOR")"
    # Rebuild if source is newer than binary
    if [[ ! -x "$TUI_SELECTOR" || "$src/main.go" -nt "$TUI_SELECTOR" ]]; then
        info "Building TUI selector..."
        (cd "$src" && go mod tidy 2>/dev/null && \
            go build -o "$TUI_SELECTOR" . 2>/dev/null) || return 1
        ok "TUI selector built"
    fi
    return 0
}

run_tui_selector() {
    local output
    output="$("$TUI_SELECTOR" --mac)"
    while IFS='=' read -r key val; do
        [[ -n "$key" ]] && declare -g "$key"="$val"
    done <<< "$output"
}

# ── Fallback bash menu ────────────────────────────────────────────────────────
show_custom_menu() {
    echo -e "\n${BOLD}${CYAN}[ CUSTOM — select tool groups ]${RESET}\n"
    ask_yes_no "  Shell environment (Zsh, Oh My Zsh, plugins, configs)?" \
        && DO_SHELL=true || DO_SHELL=false
    ask_yes_no "  AI Tools (Gemini CLI)?" \
        && DO_AI_TOOLS=true || DO_AI_TOOLS=false
    ask_yes_no "  Developer Tools (bat, fzf, jq, go, python, node...)?" \
        && DO_DEV_TOOLS=true || DO_DEV_TOOLS=false
    ask_yes_no "  Package Managers (npm, yarn, pipx, uv, rustup)?" \
        && DO_PKG_MGRS=true || DO_PKG_MGRS=false
    ask_yes_no "  Security Tools (1Password, nmap, openssl, yara, wtfis)?" \
        && DO_SECURITY=true || DO_SECURITY=false
    ask_yes_no "  Cloud / CLI (awscli, rclone)?" \
        && DO_CLOUD_CLI=true || DO_CLOUD_CLI=false
    ask_yes_no "  Nerd Fonts?" \
        && DO_FONTS=true || DO_FONTS=false
    ask_yes_no "  Projector stack (weathr, trippy, terminal animation)?" \
        && DO_PROJECTOR=true || DO_PROJECTOR=false
    ask_yes_no "  Desktop applications (iTerm2, Keka)?" \
        && DO_DESKTOP=true || DO_DESKTOP=false
}

show_menu() {
    echo -e "\n${BOLD}${BLADE}  What would you like to install?${RESET}\n"
    echo -e "  ${CYAN}[1]${RESET} Full install     — everything ${DIM}(recommended)${RESET}"
    echo -e "  ${CYAN}[2]${RESET} Shell only       — Zsh, Oh My Zsh, plugins, aliases"
    echo -e "  ${CYAN}[3]${RESET} Projector only   — Terminal animation suite"
    echo -e "  ${CYAN}[4]${RESET} Custom           — Choose individual tool groups"
    echo
    echo -en "${CYAN}  Choice [1-4]: ${RESET}"
    read -r _choice
    case "$_choice" in
        1) : ;;  # all defaults are true
        2) DO_SHELL=true; DO_AI_TOOLS=false; DO_DEV_TOOLS=false; DO_PKG_MGRS=false
           DO_SECURITY=false; DO_CLOUD_CLI=false; DO_FONTS=false
           DO_PROJECTOR=false; DO_DESKTOP=false ;;
        3) DO_SHELL=false; DO_AI_TOOLS=false; DO_DEV_TOOLS=false; DO_PKG_MGRS=false
           DO_SECURITY=false; DO_CLOUD_CLI=false; DO_FONTS=true
           DO_PROJECTOR=true; DO_DESKTOP=false ;;
        4) show_custom_menu ;;
        *) warn "Invalid choice — defaulting to full install" ;;
    esac
}

# ── Flag parsing ──────────────────────────────────────────────────────────────
# All categories default to true (install everything)
DO_SHELL=true
DO_AI_TOOLS=true
DO_DEV_TOOLS=true
DO_PKG_MGRS=true
DO_SECURITY=true
DO_CLOUD_CLI=true
DO_FONTS=true
DO_PROJECTOR=true
DO_DESKTOP=true

EXPLICIT_FLAG=false
MODE="${MODE:-batch}"

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --shell)
            DO_SHELL=true; DO_AI_TOOLS=false; DO_DEV_TOOLS=false; DO_PKG_MGRS=false
            DO_SECURITY=false; DO_CLOUD_CLI=false; DO_FONTS=false
            DO_PROJECTOR=false; DO_DESKTOP=false; EXPLICIT_FLAG=true ;;
        --projector)
            DO_SHELL=false; DO_AI_TOOLS=false; DO_DEV_TOOLS=false; DO_PKG_MGRS=false
            DO_SECURITY=false; DO_CLOUD_CLI=false; DO_FONTS=true
            DO_PROJECTOR=true; DO_DESKTOP=false; EXPLICIT_FLAG=true ;;
        --no-casks)    DO_DESKTOP=false ;;
        --interactive) MODE=interactive ;;
        --help)        show_help; exit 0 ;;
        *) err "Unknown parameter: $1"; show_help; exit 1 ;;
    esac
    shift
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Supply chain guard ────────────────────────────────────────────────────────
# shellcheck source=lib/supply_chain_guard.sh
source "$SCRIPT_DIR/lib/supply_chain_guard.sh"
# ── RC file sweep utilities (inlined) ────────────────────────────────────────

_zscaler_source_block() {
    printf '%s\n' \
        '# BEGIN terminal-kniferoll zscaler — DO NOT EDIT (managed by installer)' \
        '[ -r "$HOME/.config/terminal-kniferoll/zscaler-env.sh" ] && \' \
        '    . "$HOME/.config/terminal-kniferoll/zscaler-env.sh"' \
        '# END terminal-kniferoll zscaler'
}

backup_rc_file() {
    local rc="$1"
    [[ ! -f "$rc" ]] && return 0
    local ts; ts="$(date '+%Y%m%d-%H%M%S')"
    local backup="${rc}.terminal-kniferoll-backup-${ts}"
    cp "$rc" "$backup"
    chmod 600 "$backup"
    local dir base
    dir="$(dirname "$rc")"
    base="$(basename "$rc")"
    ls -t "${dir}/${base}.terminal-kniferoll-backup-"* 2>/dev/null | \
        tail -n +6 | while IFS= read -r _old; do rm -f "$_old"; done
    ok "  backup: $backup"
}

strip_zscaler_regions() {
    local file="$1"
    local result
    if result="$(awk '
function is_region_trigger(line) {
    if (line ~ /^[[:space:]]*(ZSC_PEM_LINUX|ZSC_PEM_MAC|ZSC_PEM)[[:space:]]*=/) return 1
    if (line ~ /^[[:space:]]*export[[:space:]]+(ZSC_PEM|CURL_CA_BUNDLE|GIT_SSL_CAINFO|SSL_CERT_FILE|REQUESTS_CA_BUNDLE|NODE_EXTRA_CA_CERTS|AWS_CA_BUNDLE|PIP_CERT|HOMEBREW_CURLOPT_CACERT)[[:space:]]*=/) return 1
    return 0
}
function is_marker_begin(line) {
    return (line ~ /^[[:space:]]*#[[:space:]]*BEGIN[[:space:]]+terminal-kniferoll[[:space:]]+zscaler/)
}
function is_marker_end(line) {
    return (line ~ /^[[:space:]]*#[[:space:]]*END[[:space:]]+terminal-kniferoll[[:space:]]+zscaler/)
}
function is_zsc_extend(line) {
    return (line ~ /^[[:space:]]*#.*[Zz]scaler/ && !is_marker_begin(line) && !is_marker_end(line))
}
function is_blank(line) { return (line ~ /^[[:space:]]*$/) }
function is_control_open(line) {
    if (line ~ /^[[:space:]]*(if|for|while|until|case)[[:space:]([]/) return 1
    if (line ~ /^[[:space:]]*function[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*[({]/) return 1
    if (line ~ /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\(\)[[:space:]]*(\{|$)/) return 1
    if (line ~ /^[[:space:]]*\{[[:space:]]*(#.*)?$/) return 1
    return 0
}
function is_control_close(line) {
    if (line ~ /^[[:space:]]*(fi|esac|done)[[:space:]]*(;[[:space:]]*(#.*)?)?$/) return 1
    if (line ~ /^[[:space:]]*\}[[:space:]]*(#.*)?$/) return 1
    return 0
}
BEGIN { in_region=0; in_marker=0; depth=0; rstart=0; pend_buf=""; pend_cnt=0 }
{
    line = $0
    if (!in_region) {
        if (depth == 0) {
            if (is_marker_begin(line)) {
                in_region=1; in_marker=1; rstart=NR; pend_buf=""; pend_cnt=0; next
            }
            if (is_region_trigger(line)) {
                in_region=1; in_marker=0; rstart=NR; pend_buf=""; pend_cnt=0; next
            }
        }
        if (is_control_open(line)) depth++
        else if (is_control_close(line) && depth > 0) depth--
        print line; next
    }
    if (in_marker) {
        if (is_marker_end(line)) {
            print "REGION " rstart " " NR > "/dev/stderr"
            in_region=0; in_marker=0
        }
        next
    }
    if (is_blank(line)) { pend_buf = pend_buf line "\n"; pend_cnt++; next }
    if (depth > 0) {
        if (is_control_open(line)) depth++
        else if (is_control_close(line) && depth > 0) depth--
        pend_buf=""; pend_cnt=0; next
    }
    if (is_region_trigger(line) || is_zsc_extend(line)) { pend_buf=""; pend_cnt=0; next }
    if (is_control_open(line)) { pend_buf=""; pend_cnt=0; depth++; next }
    print "REGION " rstart " " (NR - 1 - pend_cnt) > "/dev/stderr"
    in_region=0
    if (pend_cnt > 0) { printf "%s", pend_buf; pend_buf=""; pend_cnt=0 }
    if (is_marker_begin(line)) {
        in_region=1; in_marker=1; rstart=NR; pend_buf=""; pend_cnt=0; next
    }
    if (is_region_trigger(line)) {
        in_region=1; in_marker=0; rstart=NR; pend_buf=""; pend_cnt=0; next
    }
    if (is_control_open(line)) depth++
    else if (is_control_close(line) && depth > 0) depth--
    print line
}
END {
    if (in_region) {
        print "REGION " rstart " " NR > "/dev/stderr"
    } else if (pend_cnt > 0) {
        printf "%s", pend_buf
    }
}
' "$file" 2>/tmp/sweep-awk-err$$)"; then
        printf '%s\n' "$result"
    else
        warn "sweep-zscaler (inline) error ($file): $(head -1 /tmp/sweep-awk-err$$)"
        rm -f /tmp/sweep-awk-err$$
        cat "$file"
        return 1
    fi
    rm -f /tmp/sweep-awk-err$$
}

_has_zscaler_block() {
    grep -Eq \
        'ZSC_PEM_LINUX[[:space:]]*=|ZSC_PEM_MAC[[:space:]]*=|^[[:space:]]*unset[[:space:]]+ZSC_PEM|^[[:space:]]*(export[[:space:]]+)?ZSC_PEM[[:space:]]*=|^[[:space:]]*export[[:space:]]+(CURL_CA_BUNDLE|SSL_CERT_FILE|REQUESTS_CA_BUNDLE|NODE_EXTRA_CA_CERTS|GIT_SSL_CAINFO|AWS_CA_BUNDLE|PIP_CERT|HOMEBREW_CURLOPT_CACERT)[[:space:]]*=|# BEGIN terminal-kniferoll zscaler' \
        "$1" 2>/dev/null
}

_show_sweep_preview() {
    local rc="$1" dry="${2:-}"
    local lines_before lines_after removed_count
    lines_before=$(wc -l < "$rc")
    lines_after=$(strip_zscaler_regions "$rc" | wc -l)
    removed_count=$(( lines_before - lines_after ))
    if [[ -n "$dry" ]]; then
        info "  [dry-run] sweep: $rc"
    else
        info "  sweep: $rc"
    fi
    [[ $removed_count -gt 0 ]] && \
        info "  - removing ~${removed_count} lines (old Zscaler block)"
    info "  + appending 4 lines (new marker block)"
}

upsert_rc_zscaler_block() {
    local rc="$1" dry="${2:-}"
    [[ ! -f "$rc" ]] && return 0
    local _blk; _blk="$(mktemp)"
    _zscaler_source_block > "$_blk"
    if _has_zscaler_block "$rc"; then
        _show_sweep_preview "$rc" "$dry"
        [[ -n "$dry" ]] && { rm -f "$_blk"; return 0; }
        local _stripped; _stripped="$(mktemp)"; chmod 600 "$_stripped"
        strip_zscaler_regions "$rc" > "$_stripped"
        local _tmp; _tmp="$(mktemp)"; chmod 600 "$_tmp"
        local _stripped_content
        _stripped_content="$(cat "$_stripped")"
        if [[ -n "$_stripped_content" ]]; then
            { printf '%s\n' "$_stripped_content"; echo; cat "$_blk"; } > "$_tmp"
        else
            cat "$_blk" > "$_tmp"
        fi
        if cmp -s "$_tmp" "$rc"; then
            rm -f "$_stripped" "$_tmp" "$_blk"
            ok "$rc: Zscaler block already canonical — no backup needed"
            return 0
        fi
        backup_rc_file "$rc"
        mv -f "$_tmp" "$rc"
        rm -f "$_stripped"
        ok "$rc: Zscaler block(s) swept, source block appended"
    else
        [[ -n "$dry" ]] && {
            info "  [dry-run] $rc: no Zscaler block found — would append marker"
            rm -f "$_blk"; return 0
        }
        backup_rc_file "$rc"
        local _tmp; _tmp="$(mktemp)"; chmod 600 "$_tmp"
        { cat "$rc"; echo; cat "$_blk"; } > "$_tmp"
        mv -f "$_tmp" "$rc"
        ok "$rc: Zscaler source block appended"
    fi
    rm -f "$_blk"
}

sweep_rc_files() {
    local dry=""
    [[ "${1:-}" == "--dry-run" ]] && dry="1"
    banner "ZSCALER RC SWEEP${dry:+ (DRY RUN)}"
    local _rc
    for _rc in \
        "$HOME/.zshrc" \
        "$HOME/.zprofile" \
        "$HOME/.bashrc" \
        "$HOME/.bash_profile" \
        "$HOME/.profile"
    do
        [[ -f "$_rc" ]] && upsert_rc_zscaler_block "$_rc" "$dry"
    done
    unset _rc
}

_brew_shellenv_block() {
    cat << 'BSEOF'
# BEGIN terminal-kniferoll brew-shellenv — DO NOT EDIT (managed by installer)
if [[ -x "/opt/homebrew/bin/brew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x "/usr/local/bin/brew" ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi
# END terminal-kniferoll brew-shellenv
BSEOF
}

_brew_shellenv_block_linux() {
    cat << 'BSEOF'
# BEGIN terminal-kniferoll brew-shellenv — DO NOT EDIT (managed by installer)
if [[ -x "/home/linuxbrew/.linuxbrew/bin/brew" ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [[ -x "$HOME/.linuxbrew/bin/brew" ]]; then
    eval "$($HOME/.linuxbrew/bin/brew shellenv)"
fi
# END terminal-kniferoll brew-shellenv
BSEOF
}

_strip_brew_shellenv_regions() {
    local file="$1"
    awk '
        /# BEGIN terminal-kniferoll brew-shellenv/ { skip=1; next }
        /# END terminal-kniferoll brew-shellenv/   { skip=0; next }
        skip                                        { next }
        /eval[[:space:]]+"?\$\(.*brew shellenv/    { next }
        { print }
    ' "$file"
}

_has_brew_shellenv_block() {
    grep -Eq \
        'eval[[:space:]]+"?\$\(.*brew[[:space:]]+shellenv|# BEGIN terminal-kniferoll brew-shellenv' \
        "$1" 2>/dev/null
}

upsert_brew_shellenv_block() {
    local rc="$1" dry="${2:-}" block_fn="${3:-_brew_shellenv_block}"
    [[ ! -f "$rc" ]] && return 0
    local _blk; _blk="$(mktemp)"; chmod 600 "$_blk"
    "$block_fn" > "$_blk"
    local _clean; _clean="$(mktemp)"; chmod 600 "$_clean"
    local _final; _final="$(mktemp)"; chmod 600 "$_final"
    _strip_brew_shellenv_regions "$rc" > "$_clean"
    local _clean_content
    _clean_content="$(cat "$_clean")"
    rm -f "$_clean"
    if [[ -n "$_clean_content" ]]; then
        { printf '%s\n' "$_clean_content"; echo; cat "$_blk"; } > "$_final"
    else
        cat "$_blk" > "$_final"
    fi
    rm -f "$_blk"
    if cmp -s "$_final" "$rc"; then
        rm -f "$_final"
        return 0
    fi
    if [[ -n "$dry" ]]; then
        info "  [dry-run] sweep (brew-shellenv): $rc"
        rm -f "$_final"
        return 0
    fi
    backup_rc_file "$rc"
    mv -f "$_final" "$rc"
    ok "$rc: brew-shellenv block upserted"
}

sweep_brew_shellenv_files() {
    local dry="" block_fn="${2:-_brew_shellenv_block}"
    [[ "${1:-}" == "--dry-run" ]] && dry="1"
    banner "BREW SHELLENV RC SWEEP${dry:+ (DRY RUN)}"
    local _rc
    for _rc in \
        "$HOME/.zshrc" \
        "$HOME/.zprofile" \
        "$HOME/.bashrc" \
        "$HOME/.bash_profile" \
        "$HOME/.profile"
    do
        [[ -f "$_rc" ]] && upsert_brew_shellenv_block "$_rc" "$dry" "$block_fn"
    done
    unset _rc
}

# ── ASCII banner ──────────────────────────────────────────────────────────────
echo -e "${BOLD}${CYAN}"
cat << 'BANNER'
  ╔════════════════════════════════════╗
  ║  ⌁  terminal-kniferoll            ║
  ║     sharp tools. clean cuts.      ║
  ╚════════════════════════════════════╝
BANNER
echo -e "${RESET}"
quip "Log: $LOG_FILE"
echo

# ── TLS preflight + Zscaler trust (hard gate) ────────────────────────────────
# proceeding with a broken TLS stack would silently corrupt every download.
# preflight_zscaler_check exit codes:
#   0 — clean, proceed
#   1 — SSL cert error → run setup_zscaler_trust --required
#   2 — HTML splash page handled (auto-accept or manual) → re-run preflight
banner "TLS PREFLIGHT"
_preflight_rc=0
preflight_zscaler_check || _preflight_rc=$?

if [[ "$_preflight_rc" -eq 2 ]]; then
    # Splash page was accepted (auto or manual) — re-validate once
    info "Re-validating TLS after Zscaler acknowledgment..."
    _preflight_rc=0
    preflight_zscaler_check || _preflight_rc=$?
    if [[ "$_preflight_rc" -ne 0 ]]; then
        die "TLS still blocked after Zscaler acceptance — check $LOG_FILE"
    fi
fi

if [[ "$_preflight_rc" -eq 1 ]]; then
    banner "MANAGED DEVICE SETUP — REQUIRED"
    info "TLS interception detected — configuring Zscaler cert trust before proceeding"
    setup_zscaler_trust --required

    info "Re-validating TLS after trust setup..."
    _preflight_rc=0
    preflight_zscaler_check || _preflight_rc=$?
    if [[ "$_preflight_rc" -ne 0 ]]; then
        err "TLS validation failed even after Zscaler cert trust was configured."
        err ""
        err "Possible causes:"
        err "  - The Zscaler cert bundle is incomplete or expired"
        err "  - A different corporate proxy is intercepting (not Zscaler)"
        err "  - Network connectivity issue (VPN not connected?)"
        err ""
        err "Log: $LOG_FILE"
        die "TLS still broken after trust setup — aborting install"
    fi
    ok "TLS re-validated — all subsequent curl/brew/git installs will use the Zscaler CA bundle"
else
    # Opportunistic cert detection: wire up env vars for tool configuration
    # even on non-managed devices that happen to have a Zscaler cert present.
    setup_zscaler_trust
fi

# ── Homebrew bootstrap ────────────────────────────────────────────────────────
# Triple-redundant check: explicit canonical paths + PATH-based fallback.
# Covers: PATH-stripping sudo, non-login shells, fresh CI environments.
_brew_is_installed() {
    [[ -x /opt/homebrew/bin/brew ]] || \
    [[ -x /usr/local/bin/brew    ]] || \
    command -v brew &>/dev/null
}
if ! _brew_is_installed; then
    info "Installing Homebrew..."
    brew_script="$(download_to_tmp \
        "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh" \
        "homebrew-install-XXXXXX.sh")"
    # Hard gate: if Homebrew fails to install, nothing else can succeed.
    if ! env NONINTERACTIVE=1 /bin/bash "$brew_script"; then
        rm -f "$brew_script"
        die "Homebrew installation failed — cannot continue without a package manager"
    fi
    rm -f "$brew_script"
    ok "Homebrew installed"
else
    skip "Homebrew already installed"
fi

if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi

# Fix Homebrew share directory permissions to prevent oh-my-zsh compaudit warnings.
# Homebrew sets /opt/homebrew/share group-writable (admin), which OMZ flags as insecure.
if [[ -d /opt/homebrew/share ]]; then
    run_optional "Hardening /opt/homebrew/share permissions" \
        chmod g-w,o-w /opt/homebrew/share
fi

# Upsert brew shellenv block into ~/.zprofile, ~/.zshrc, ~/.bashrc, etc.
# Uses marker-comment pattern (same as Zscaler sweep) — idempotent across runs.
# Replaces older bare eval "$(brew shellenv)" lines installed by previous versions.
if _brew_is_installed; then
    sweep_brew_shellenv_files
fi

# ── Install Go early (needed to build TUI selector) ──────────────────────────
if ! is_installed "go" && is_installed "brew"; then
    run_optional "Installing Go (TUI prerequisite)" brew install go
fi

# ── Show TUI or fallback menu ─────────────────────────────────────────────────
if [[ "$EXPLICIT_FLAG" == "false" ]] && { [[ -t 0 ]] || [[ "$MODE" == "interactive" ]]; }; then
    if build_tui_selector && [[ -x "$TUI_SELECTOR" ]]; then
        run_tui_selector
    else
        show_menu
    fi
fi

info "Supply chain: strict (TLS enforced, hashes verified where available)"

# ── Evict tools removed from this project ─────────────────────────────────────
banner "HOUSEKEEPING — EVICTING REMOVED TOOLS"
cleanup_removed_tools

# ────────────────────────────────────────────────────────────────────────────
# 1. CORE PREREQUISITES
# ────────────────────────────────────────────────────────────────────────────
banner "CORE PREREQUISITES"
run_optional "Updating Homebrew" brew update

# ────────────────────────────────────────────────────────────────────────────
# 2. SHELL ENVIRONMENT
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_SHELL" == "true" ]]; then
    banner "SHELL ENVIRONMENT"

    if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
        # Pinned to a specific release tag instead of piping master/install.sh.
        # GIT_SSL_CAINFO is already exported (set in _zscaler_export_env above) so
        # this clone trusts the Zscaler CA on managed devices.
        # Update OMZ_TAG when upgrading. Tags: https://github.com/ohmyzsh/ohmyzsh/tags
        OMZ_TAG="24.9.0"
        info "Cloning Oh My Zsh at tag ${OMZ_TAG} (pinned)..."
        if ! git clone --depth 1 --branch "$OMZ_TAG" \
                https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh" 2>/dev/null; then
            warn "Tag ${OMZ_TAG} not found — falling back to install.sh (unpinned)"
            omz_script="$(download_to_tmp \
                "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh" \
                "ohmyzsh-install-XXXXXX.sh")"
            # TLS preflight already passed; failure here is a real error.
            if ! RUNZSH=no CHSH=no bash "$omz_script" --unattended; then
                rm -f "$omz_script"
                die "Oh My Zsh installation failed — TLS was validated but the install script returned non-zero"
            fi
            rm -f "$omz_script"
            ok "Oh My Zsh installed (unpinned fallback)"
        else
            ok "Oh My Zsh cloned at ${OMZ_TAG}"
        fi
    else
        skip "Oh My Zsh already installed"
    fi

    ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
    mkdir -p "$ZSH_CUSTOM/plugins"

    # Plugin versions — update tags here when upgrading
    # zsh-autosuggestions tags: https://github.com/zsh-users/zsh-autosuggestions/tags
    ZSH_AUTOSUG_TAG="v0.7.1"
    # fast-syntax-highlighting tags: https://github.com/zdharma-continuum/fast-syntax-highlighting/tags
    ZSH_FSH_TAG="v1.55"

    [[ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]] || \
        run_optional "Installing zsh-autosuggestions ${ZSH_AUTOSUG_TAG}" \
            git clone --depth=1 --branch "$ZSH_AUTOSUG_TAG" \
                https://github.com/zsh-users/zsh-autosuggestions \
                "$ZSH_CUSTOM/plugins/zsh-autosuggestions"

    # fast-syntax-highlighting MUST be last plugin loaded
    [[ -d "$ZSH_CUSTOM/plugins/fast-syntax-highlighting" ]] || \
        run_optional "Installing fast-syntax-highlighting ${ZSH_FSH_TAG}" \
            git clone --depth=1 --branch "$ZSH_FSH_TAG" \
                https://github.com/zdharma-continuum/fast-syntax-highlighting \
                "$ZSH_CUSTOM/plugins/fast-syntax-highlighting"

    banner "DEPLOYING SHELL CONFIGS"
    mkdir -p "$HOME/.shell"
    if [[ ! -f "$HOME/.zshrc" ]]; then
        cp "$SCRIPT_DIR/shell/zshrc.zsh" "$HOME/.zshrc"
        ok "~/.zshrc deployed (fresh install)"
    fi
    cp "$SCRIPT_DIR/shell/aliases.zsh" "$HOME/.shell/aliases.zsh"
    cp "$SCRIPT_DIR/shell/plugins.zsh" "$HOME/.shell/plugins.zsh"
    ok "Shell configurations deployed"

    # macOS-specific aliases
    if [[ ! -f "$HOME/.shell/aliases_mac.zsh" ]]; then
        echo 'alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"' \
            > "$HOME/.shell/aliases_mac.zsh"
        echo 'alias sudo="sudo -E"' >> "$HOME/.shell/aliases_mac.zsh"
    fi
    # shellcheck disable=SC2016  # single quotes intentional: written to ~/.zshrc, expands on source
    grep -q "aliases_mac.zsh" "$HOME/.zshrc" || \
        echo '[[ -f "$HOME/.shell/aliases_mac.zsh" ]] && source "$HOME/.shell/aliases_mac.zsh"' \
            >> "$HOME/.zshrc"

    # Ensure /opt/homebrew/bin is in PATH for non-login shells (Terminal.app, VS Code, etc.)
    if [[ -d /opt/homebrew/bin ]]; then
        # shellcheck disable=SC2016  # single quotes intentional: written to rc files, expands on source
        _brew_path_line='[[ -x /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"'
        append_if_missing "$HOME/.zprofile" "$_brew_path_line"
        append_if_missing "$HOME/.zshrc"    "$_brew_path_line"
        [[ ":$PATH:" != *":/opt/homebrew/bin:"* ]] && \
            export PATH="/opt/homebrew/bin:$PATH" && \
            ok "/opt/homebrew/bin added to current session PATH"
        ok "Homebrew PATH ensured in ~/.zprofile and ~/.zshrc"
    fi
fi

# ────────────────────────────────────────────────────────────────────────────
# 3. AI TOOLS
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_AI_TOOLS" == "true" ]]; then
    banner "AI TOOLS"
    if ! is_installed "gemini"; then
        run_optional "Installing Gemini CLI" brew install gemini-cli
        ! is_installed "gemini" && is_installed "npm" && \
            run_optional "Installing Gemini CLI (npm fallback)" \
                npm install -g @google/gemini-cli || true
    else
        skip "Gemini CLI already installed"
    fi
fi

# ────────────────────────────────────────────────────────────────────────────
# 4. DEVELOPER TOOLS
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_DEV_TOOLS" == "true" ]]; then
    banner "DEVELOPER TOOLS"
    DEV_PACKAGES=(
        bat binutils btop cbonsai cmatrix exiftool
        fastfetch fontconfig freetype fzf gcc gh git gzip
        harfbuzz hexyl jq lolcat lsd lua lz4 lzo m4 micro ncurses
        nushell speedtest-cli sqlite starship tealdeer tmux
        yazi zoxide zsh-autosuggestions zsh-fast-syntax-highlighting
        # Language runtimes
        go openjdk python@3.12 ruby
    )
    for pkg in "${DEV_PACKAGES[@]}"; do
        if brew list "$pkg" &>/dev/null 2>&1; then
            skip "$pkg"
        else
            run_optional "Installing $pkg" brew install "$pkg" || FAILED_TOOLS+=("$pkg")
        fi
    done

    # Upgrade pip and run TLS smoke tests.
    # PIP_CERT is already set if Zscaler is active, so pip inherits the CA bundle.
    # 'local' is only valid inside a function; use plain assignment here.
    _py3="$(command -v python3.12 || command -v python3 || true)"
    if [[ -n "$_py3" ]]; then
        # PEP 668 (Homebrew Python, macOS system Python): pip upgrade may be
        # managed externally.  Detect the sentinel and skip the upgrade.
        _py3_stdlib="$("$_py3" -c 'import sysconfig; print(sysconfig.get_path("stdlib"))' 2>/dev/null || true)"
        if [[ -n "$_py3_stdlib" && -f "$(dirname "$_py3_stdlib")/EXTERNALLY-MANAGED" ]]; then
            skip "pip upgrade — Python is externally-managed (PEP 668); package manager owns pip"
        else
            run_optional "Upgrading pip" "$_py3" -m pip install --upgrade pip
        fi
        run_optional "Python TLS smoke test (ssl.create_default_context)" \
            "$_py3" -c "import ssl; ssl.create_default_context().load_default_certs(); print('SSL OK')"
        run_optional "pip dry-run TLS test (requests)" \
            "$_py3" -m pip install --dry-run requests 2>&1 | grep -E "(Requirement|Would|Could)" || true
    fi
fi

# ────────────────────────────────────────────────────────────────────────────
# 5. PACKAGE MANAGERS
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_PKG_MGRS" == "true" ]]; then
    banner "PACKAGE MANAGERS"

    # Node.js + npm
    if brew list node &>/dev/null 2>&1 || is_installed "node"; then
        skip "node (npm)"
    else
        run_optional "Installing node + npm" brew install node || FAILED_TOOLS+=("node")
    fi

    # yarn
    if is_installed "yarn"; then
        skip "yarn"
    else
        # Prefer brew cask for yarn classic (v1)
        run_optional "Installing yarn" brew install yarn || \
            { is_installed "npm" && \
              run_optional "Installing yarn (npm fallback)" npm install -g yarn; } || \
            FAILED_TOOLS+=("yarn")
    fi

    # pipx + uv (Python package managers)
    for pkg in pipx uv; do
        if brew list "$pkg" &>/dev/null 2>&1 || is_installed "$pkg"; then
            skip "$pkg"
        else
            run_optional "Installing $pkg" brew install "$pkg" || FAILED_TOOLS+=("$pkg")
        fi
    done
    is_installed "pipx" && run_optional "Configuring pipx path" pipx ensurepath

    # Rust / cargo via rustup
    if brew list rustup &>/dev/null 2>&1 || is_installed "rustup"; then
        skip "rustup"
    else
        run_optional "Installing rustup" brew install rustup || FAILED_TOOLS+=("rustup")
    fi
fi

# ────────────────────────────────────────────────────────────────────────────
# 6. SECURITY TOOLS
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_SECURITY" == "true" ]]; then
    banner "SECURITY TOOLS"

    # 1Password CLI
    if is_installed "op"; then
        skip "1Password CLI already installed"
    else
        run_optional "Installing 1Password CLI" brew install --cask 1password-cli
        is_installed "op" || warn "1Password CLI (op) not found on PATH after install"
    fi
    mkdir -p "$HOME/.1password"

    SECURITY_PACKAGES=(
        ca-certificates gnutls nmap ngrep openssl@3 tcpdump unbound wireshark yara
    )
    for pkg in "${SECURITY_PACKAGES[@]}"; do
        if brew list "$pkg" &>/dev/null 2>&1; then
            skip "$pkg"
        else
            run_optional "Installing $pkg" brew install "$pkg" || FAILED_TOOLS+=("$pkg")
        fi
    done

    # wtfis via pipx
    is_installed "wtfis" || {
        run_optional "Installing wtfis via pipx" pipx install wtfis
        run_optional "Configuring pipx path"     pipx ensurepath
    }
fi

# ────────────────────────────────────────────────────────────────────────────
# 7. CLOUD / CLI
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_CLOUD_CLI" == "true" ]]; then
    banner "CLOUD / CLI"

    # AWS CLI
    if is_installed "aws"; then
        skip "AWS CLI already installed"
    else
        run_optional "Installing AWS CLI" brew install awscli || FAILED_TOOLS+=("awscli")
    fi

    # rclone
    if brew list rclone &>/dev/null 2>&1 || is_installed "rclone"; then
        skip "rclone"
    else
        run_optional "Installing rclone" brew install rclone || FAILED_TOOLS+=("rclone")
    fi
fi

# ────────────────────────────────────────────────────────────────────────────
# 8. DESKTOP APPLICATIONS (Casks)
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_DESKTOP" == "true" ]]; then
    banner "DESKTOP APPLICATIONS"

    _restricted=false
    if is_restricted_device; then
        _restricted=true
        info "Managed device detected — cask installs may require admin approval"
    fi

    if is_app_installed "iTerm"; then
        skip "iTerm2 already installed"
    else
        [[ "$_restricted" == "true" ]] && \
            quip "Restricted device — iTerm2 may need Self Service or manual install"
        run_optional "Installing iTerm2" brew install --cask iterm2
        is_app_installed "iTerm" || warn "iTerm2 not found — install manually or via Self Service"
    fi

    if is_app_installed "Keka"; then
        skip "Keka already installed"
    else
        [[ "$_restricted" == "true" ]] && \
            quip "Restricted device — Keka may need Self Service or manual install"
        run_optional "Installing Keka" brew install --cask keka
        is_app_installed "Keka" || warn "Keka not found — install manually or via Self Service"
    fi
fi

# ────────────────────────────────────────────────────────────────────────────
# 9. NERD FONTS
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_FONTS" == "true" ]]; then
    FONT_DIR="$HOME/Library/Fonts"
    NERD_FONTS=(
        Iosevka Hack UbuntuMono JetBrainsMono 3270
        FiraCode CascadiaCode VictorMono Mononoki
        SpaceMono SourceCodePro Meslo GeistMono
    )
    NERD_FONTS_VER="v3.4.0"
    banner "NERD FONTS"
    mkdir -p "$FONT_DIR"
    for _nf in "${NERD_FONTS[@]}"; do
        if find "$FONT_DIR" -maxdepth 1 -iname "*${_nf}*" -print -quit 2>/dev/null | grep -q .; then
            skip "$_nf Nerd Font already installed"
            continue
        fi
        _font_zip="$(mktemp /tmp/font-XXXXXX.zip)"
        _font_extract="$(mktemp -d /tmp/font-extract-XXXXXX)"
        _font_curl_opts=(--proto '=https' --tlsv1.2 -fsSL)
        [[ -n "${CURL_CA_BUNDLE:-}" && -f "${CURL_CA_BUNDLE}" ]] && \
            _font_curl_opts+=(--cacert "$CURL_CA_BUNDLE")
        if curl "${_font_curl_opts[@]}" \
                "https://github.com/ryanoasis/nerd-fonts/releases/download/${NERD_FONTS_VER}/${_nf}.zip" \
                -o "$_font_zip"; then
            unzip -qo "$_font_zip" -d "$_font_extract"
            find "$_font_extract" -name "*.ttf" -exec cp {} "$FONT_DIR/" \;
            ok "$_nf Nerd Font installed"
        else
            warn "$_nf Nerd Font download failed"
            FAILED_TOOLS+=("font:$_nf")
        fi
        rm -rf "$_font_zip" "$_font_extract"
    done
fi

# ────────────────────────────────────────────────────────────────────────────
# 10. PROJECTOR STACK
# ────────────────────────────────────────────────────────────────────────────
if [[ "$DO_PROJECTOR" == "true" ]]; then
    banner "PROJECTOR STACK"
    ensure_rust_toolchain

    is_installed "weathr" || run_optional "Installing weathr via cargo" cargo install weathr
    is_installed "trip"   || run_optional "Installing trippy via cargo" cargo install trippy

    banner "PROJECTOR CONFIGURATION"
    mkdir -p "$HOME/.config/projector"
    [[ -f "$HOME/.config/projector/config.json" ]] || \
        cp "$SCRIPT_DIR/projector/config.json.default" "$HOME/.config/projector/config.json"
    [[ -f "$SCRIPT_DIR/projector.py" ]] && chmod +x "$SCRIPT_DIR/projector.py" || true
    ok "Projector configuration deployed"
fi

# ────────────────────────────────────────────────────────────────────────────
# 11. TERMINAL THEME
# ────────────────────────────────────────────────────────────────────────────
banner "TERMINAL THEME"
ITERM_THEME_SRC="$SCRIPT_DIR/macos/Cyberwave.itermcolors"
ITERM_PREFS_DIR="$HOME/Library/Application Support/iTerm2"

if [[ -f "$ITERM_THEME_SRC" ]]; then
    if [[ -d "/Applications/iTerm.app" ]]; then
        mkdir -p "$ITERM_PREFS_DIR"
        _dest="$ITERM_PREFS_DIR/Cyberwave.itermcolors"
        if [[ ! -f "$_dest" ]]; then
            cp "$ITERM_THEME_SRC" "$_dest"
            ok "Cyberwave theme staged — opening iTerm2 to import"
            quip "Preferences → Profiles → Colors → Color Presets… → Import…"
            open "$_dest" 2>/dev/null || warn "Could not auto-open theme; import manually from $_dest"
        else
            skip "Cyberwave iTerm2 theme already staged"
        fi
    else
        warn "iTerm2 not found — theme file is at: $ITERM_THEME_SRC"
        quip "Install iTerm2, then double-click the file above to import Cyberwave"
    fi
else
    warn "Cyberwave theme source not found — run from repo root"
fi

# ────────────────────────────────────────────────────────────────────────────
# 12. ZSCALER ENV FILE + RC SWEEP (every invocation, any mode)
# ────────────────────────────────────────────────────────────────────────────
write_zscaler_env_file
sweep_rc_files

# ────────────────────────────────────────────────────────────────────────────
# 13. BREW SHELLENV RC SWEEP (idempotent; also re-run here to catch cases
#     where the sweep earlier in the script was skipped because brew wasn't
#     installed yet at that point but was installed by a package step above)
# ────────────────────────────────────────────────────────────────────────────
if _brew_is_installed; then
    sweep_brew_shellenv_files
fi

# ────────────────────────────────────────────────────────────────────────────
# SUMMARY
# ────────────────────────────────────────────────────────────────────────────
sc_process_deferred
print_summary
sc_summary

# ── Brew login-shell verification ─────────────────────────────────────────────
# Spawn a clean login shell to confirm brew is on PATH after rc file updates.
if _brew_is_installed; then
    _brew_login_path="$(/bin/zsh -l -c 'command -v brew' 2>/dev/null || true)"
    if [[ -n "$_brew_login_path" ]]; then
        ok "brew verification: findable from a clean zsh login shell (${_brew_login_path})"
    else
        warn "brew installed but NOT findable in a clean zsh login shell"
        warn "Add to ~/.zprofile manually:"
        warn '  if [[ -x "/opt/homebrew/bin/brew" ]]; then'
        warn '      eval "$(/opt/homebrew/bin/brew shellenv)"'
        warn '  elif [[ -x "/usr/local/bin/brew" ]]; then'
        warn '      eval "$(/usr/local/bin/brew shellenv)"'
        warn '  fi'
    fi
fi

echo -e "${BOLD}${CYAN}>>> mission complete. knives sharp. out.${RESET}"
echo -e "${DIM}    Reminder: restart your shell or run 'source ~/.zshrc' to activate.${RESET}"
